iptables_renders:
  filter:
    input: |
      -A INPUT -j ACCEPT
    forward: |
      -A FORWARD -m state --state RELATED,ESTABLISHED -m comment --comment allow-existing-connections -j ACCEPT
      -A FORWARD -j ACCEPT